<h1>Пройденные опросы: </h1>
<form action="/dates" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <label>
    <br>
    Выберите дату опроса:<br>
    <select name="days">
		 	<?php foreach ($dates as $date): ?>
		  <option value="<?= $date['date']?>"><?= $date['date']?></option>
			<?php endforeach ?>
    </select>
  </label>
  <input type="submit" value="Search" />
</form>
	<?php foreach ($dates as $date): ?>
		<table>
		  <tr>
		    <td>1:</td>
		    <td>2:</td>
		    <td>3:</td>
		    <td>4:</td>
		    <td>5:</td>
		    <td>6:</td>
		    <td>7:</td>
		  </tr>
		  <tr>
		    <td><?= htmlspecialchars($date['title'] ?? '') ?></td>
		    <td><?= htmlspecialchars($date['date'] ?? '') ?></td>
		    <td><?= htmlspecialchars($date['adults'] ?? '') ?></td>
		    <td><?= htmlspecialchars($date['children'] ?? '') ?></td>
		    <td><?= htmlspecialchars($date['transfer'] ?? '') ?></td>
		    <td><?= htmlspecialchars($date['name'] ?? '') ?></td>
		    <td><?= htmlspecialchars($date['email'] ?? '') ?></td>
		  </tr>
		  <tr>
		    <td><?= htmlspecialchars($cost ?? '') ?>$</td>
		    <td></td>
		    <td><?= htmlspecialchars($subCosts['adults'] ?? '') ?>$</td>
		    <td><?= htmlspecialchars($subCosts['children'] ?? '') ?>$</td>
		    <td><?= htmlspecialchars($subCosts['transfer'] ?? '') ?>$</td>
		    <td></td>
		    <td></td>
		  </tr>
		</table>
		<h3>Итого: <?= htmlspecialchars($total ?? '') ?>$</h3>
		<br>
		<br>
	<?php endforeach ?>
<p></p>

  <style type="text/css">
   td { 
    border: 1px solid #ccccee;
    padding: 4px 10px;
   }
  </style>