<h1>Опрос</h1>
<h2>1</h2>
<form action="/dates" method="post">
<input type="hidden" name="date[price]" value="280">
<input type="text" name="date[title]" value="Название опроса">
  <div>
    <label>
      <br>
      Выберите дату:<br>
      <select name="date[date]">
        <option <?= isset($date['date']) && $date['date'] === '2019-09-10' ? 'selected' : '' ?> value="2019-09-10">2019-09-10</option>
        <option <?= isset($date['date']) && $date['date'] === '2019-10-10' ? 'selected' : '' ?> value="2019-10-10">2019-10-10</option>
        <option <?= isset($date['date']) && $date['date'] === '2019-10-18' ? 'selected' : '' ?> value="2019-10-18">2019-10-18</option>
      </select>
    </label>
    <?php if (isset($errors['date'])): ?>
      <div style="color: red"><?= $errors['date'] ?></div>
    <?php endif ?>
  </div>
  <br>

  <div>
    <label>
        Имя<br>
      <input type="text" name="date[name]" value="<?= htmlspecialchars($date['name'] ?? '') ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
      <div style="color: red"><?= $errors['name'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Email<br>
      <input type="email" name="date[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
    </label>
    <?php if (isset($errors['email'])): ?>
      <div style="color: red"><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
      <br>
      Первый вопрос:<br>
      <select name="date[adults]">
        <option <?= isset($date['adults']) && $date['adults'] === '1' ? 'selected' : '' ?> value="1">1</option>
        <option <?= isset($date['adults']) && $date['adults'] === '2' ? 'selected' : '' ?> value="2">2</option>
        <option <?= isset($date['adults']) && $date['adults'] === '3' ? 'selected' : '' ?> value="3">3</option>
        <option <?= isset($date['adults']) && $date['adults'] === '4' ? 'selected' : '' ?> value="4">4</option>
        <option <?= isset($date['adults']) && $date['adults'] === '5' ? 'selected' : '' ?> value="5">5</option>
        <option <?= isset($date['adults']) && $date['adults'] === '6' ? 'selected' : '' ?> value="6">6</option>
        <option <?= isset($date['adults']) && $date['adults'] === '7' ? 'selected' : '' ?> value="7">7</option>
        <option <?= isset($date['adults']) && $date['adults'] === '8' ? 'selected' : '' ?> value="8">8</option>
      </select>
    </label>
    <?php if (isset($errors['adults'])): ?>
      <div style="color: red"><?= $errors['adults'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
      <br>
      Второй вопрос:<br>
      <select name="date[children]">
        <option <?= isset($date['children']) && $date['children'] === '0' ? 'selected' : '' ?> value="0">Нет</option>
        <option <?= isset($date['children']) && $date['children'] === '1' ? 'selected' : '' ?> value="1">1</option>
        <option <?= isset($date['children']) && $date['children'] === '2' ? 'selected' : '' ?> value="2">2</option>
        <option <?= isset($date['children']) && $date['children'] === '3' ? 'selected' : '' ?> value="3">3</option>
        <option <?= isset($date['children']) && $date['children'] === '4' ? 'selected' : '' ?> value="4">4</option>
        <option <?= isset($date['children']) && $date['children'] === '5' ? 'selected' : '' ?> value="5">5</option>
        <option <?= isset($date['children']) && $date['children'] === '6' ? 'selected' : '' ?> value="6">6</option>
        <option <?= isset($date['children']) && $date['children'] === '7' ? 'selected' : '' ?> value="7">7</option>
        <option <?= isset($date['children']) && $date['children'] === '8' ? 'selected' : '' ?> value="8">8</option>
      </select>
    </label>
    <?php if (isset($errors['children'])): ?>
      <div style="color: red"><?= $errors['children'] ?></div>
    <?php endif ?>
    <?php if (isset($errors['children_quantity'])): ?>
      <div style="color: red"><?= $errors['children_quantity'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
      <br>
      Ещё что-то:<br>
      <select name="date[transfer]">
        <option <?= isset($date['transfer']) && $date['transfer'] === 'none' ? 'selected' : '' ?> value="none">Да</option>
        <option <?= isset($date['transfer']) && $date['transfer'] === 'include' ? 'selected' : '' ?> value="include">Нет</option>
      </select>
    </label>
    <?php if (isset($errors['children'])): ?>
      <div style="color: red"><?= $errors['children'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <div>
    <label>
      Отправить на сервер?
      <input type="text" name="date[confirm]">
    </label>
    <?php if (isset($errors['confirm'])): ?>
      <div style="color: red"><?= $errors['confirm'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <input type="submit" value="Отправить">
</form>

<table>
  <tr>
    <td>1:</td>
    <td>2:</td>
    <td>3:</td>
    <td>4:</td>
    <td>5:</td>
    <td>6:</td>
    <td>7:</td>
  </tr>
  <tr>
    <td><?= htmlspecialchars($date['title'] ?? '') ?></td>
    <td><?= htmlspecialchars($date['date'] ?? '') ?></td>
    <td><?= htmlspecialchars($date['adults'] ?? '') ?></td>
    <td><?= htmlspecialchars($date['children'] ?? '') ?></td>
    <td><?= htmlspecialchars($date['transfer'] ?? '') ?></td>
    <td><?= htmlspecialchars($date['name'] ?? '') ?></td>
    <td><?= htmlspecialchars($date['email'] ?? '') ?></td>
  </tr>
  <tr>
    <td><?= htmlspecialchars($cost ?? '') ?></td>
    <td></td>
    <td><?= htmlspecialchars($subCosts['adults'] ?? '') ?></td>
    <td><?= htmlspecialchars($subCosts['children'] ?? '') ?></td>
    <td><?= htmlspecialchars($subCosts['transfer'] ?? '') ?></td>
    <td></td>
    <td></td>
  </tr>
</table>
<h2>Итого: <?= htmlspecialchars($total ?? '') ?></h2>

  <style type="text/css">
   td { 
    border: 1px solid #ccccee;
    padding: 4px 10px;
   }
  </style>